version: "3.1"
services:

    emag-postgres:
      image: postgres:9.6-alpine
      container_name: emag-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=emag

    emag-webserver:
      image: nginx:alpine
      container_name: emag-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/emag-webserver/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"
      expose:
          - "8081"
      environment:
          - VIRTUAL_HOST=emag.test 
    emag-php-fpm:
      build: docker/emag-php-fpm
      container_name: emag-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/emag-php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    emag-nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: emag-nginx-proxy
      ports:
          - "80:80"
      links:
          - emag-webserver
      volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro     

